version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - MAGIC_NAME=TOR
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
